import {
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowUpDown,
  ArrowUpRight,
  Banknote,
  Bell,
  Box,
  Boxes,
  Building,
  Building2,
  Calculator,
  Calendar,
  CalendarArrowDown,
  CalendarRange,
  Camera,
  ChartColumn,
  ChartLine,
  ChartPie,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight,
  Circle,
  CircleAlert,
  CircleCheck,
  CircleDashed,
  CircleHelp,
  CircleUser,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Clock4,
  Columns3,
  CreditCard,
  Database,
  Download,
  Ellipsis,
  EllipsisVertical,
  ExternalLink,
  Eye,
  EyeOff,
  Factory,
  File,
  FileBadge,
  FileChartColumn,
  FileSpreadsheet,
  FileText,
  Folder,
  FolderX,
  Forklift,
  Funnel,
  Globe,
  Hammer,
  HardHat,
  Hourglass,
  House,
  IdCard,
  ImageOff,
  Inbox,
  IndianRupee,
  Key,
  LayoutDashboard,
  LayoutGrid,
  Lightbulb,
  List,
  ListChecks,
  Loader,
  LoaderCircle,
  Lock,
  LockKeyhole,
  LogOut,
  MailCheck,
  MapPin,
  Megaphone,
  Menu,
  Minus,
  OctagonAlert,
  Package,
  PackageMinus,
  PackagePlus,
  PackageX,
  PanelLeftClose,
  PanelLeftOpen,
  Plus,
  QrCode,
  Receipt,
  ReceiptText,
  RefreshCw,
  RotateCcw,
  Route,
  Save,
  Search,
  Send,
  Settings,
  Shapes,
  Shield,
  ShieldCheck,
  ShoppingCart,
  SlidersHorizontal,
  Sparkles,
  SquarePen,
  Store,
  Table,
  Tag,
  Trash2,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  Truck,
  Upload,
  User,
  UserMinus,
  Users,
  Wallet,
  Warehouse,
  X,
  Zap,
} from "lucide-react";

const ICONS = {
  adjustments: SlidersHorizontal,
  "alert-circle": CircleAlert,
  "alert-octagon": OctagonAlert,
  "building-factory-2": Factory,
  "building-skyscraper": Building2,
  "chart-donut": ChartPie,
  columns: Columns3,
  folder: Folder,
  "hard-hat": HardHat,
  hourglass: Hourglass,
  "layout-sidebar-left-collapse": PanelLeftClose,
  "layout-sidebar-left-expand": PanelLeftOpen,
  minus: Minus,
  "progress-alert": CircleDashed,
  "trending-down": TrendingDown,
  "truck-loading": Truck,
  "alert-triangle": TriangleAlert,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-up-right": ArrowUpRight,
  "arrows-exchange": ArrowLeftRight,
  "arrows-transfer-up": ArrowUpDown,
  bell: Bell,
  bolt: Zap,
  box: Box,
  building: Building,
  "building-community": Building2,
  "building-off": Building,
  "building-store": Store,
  "building-warehouse": Warehouse,
  bulb: Lightbulb,
  calculator: Calculator,
  calendar: Calendar,
  "calendar-down": CalendarArrowDown,
  "calendar-week": CalendarRange,
  camera: Camera,
  cash: Banknote,
  category: Shapes,
  "chart-bar": ChartColumn,
  "chart-line": ChartLine,
  check: Check,
  checklist: ListChecks,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevrons-left": ChevronsLeft,
  "chevrons-right": ChevronsRight,
  "chevron-right": ChevronRight,
  "circle-check": CircleCheck,
  "clipboard-check": ClipboardCheck,
  "clipboard-text": ClipboardList,
  clock: Clock,
  "clock-hour-4": Clock4,
  "columns-3": Columns3,
  "credit-card": CreditCard,
  "currency-rupee": IndianRupee,
  "database-off": Database,
  "device-floppy": Save,
  dots: Ellipsis,
  "dots-vertical": EllipsisVertical,
  download: Download,
  edit: SquarePen,
  "external-link": ExternalLink,
  eye: Eye,
  "eye-off": EyeOff,
  file: File,
  "file-certificate": FileBadge,
  "file-description": FileText,
  "file-document": FileText,
  "file-invoice": ReceiptText,
  "file-spreadsheet": FileSpreadsheet,
  "file-text": FileText,
  filter: Funnel,
  "folder-off": FolderX,
  forklift: Forklift,
  hammer: Hammer,
  "help-circle": CircleHelp,
  home: House,
  "id-badge-2": IdCard,
  inbox: Inbox,
  key: Key,
  "layout-dashboard": LayoutDashboard,
  "layout-grid": LayoutGrid,
  "list-details": List,
  loader: Loader,
  "loader-2": LoaderCircle,
  lock: Lock,
  "lock-access": LockKeyhole,
  logout: LogOut,
  "logout-2": LogOut,
  "mail-check": MailCheck,
  "mail-fast": Send,
  "map-pin": MapPin,
  "menu-2": Menu,
  package: Package,
  "package-export": PackageMinus,
  "package-import": PackagePlus,
  "package-off": PackageX,
  packages: Boxes,
  "photo-off": ImageOff,
  plus: Plus,
  qrcode: QrCode,
  receipt: Receipt,
  "receipt-2": Receipt,
  refresh: RefreshCw,
  "report-analytics": FileChartColumn,
  "rotate-2": RotateCcw,
  route: Route,
  search: Search,
  settings: Settings,
  "shield-check": ShieldCheck,
  "shield-lock": Shield,
  "shopping-cart": ShoppingCart,
  sparkles: Sparkles,
  speakerphone: Megaphone,
  table: Table,
  tag: Tag,
  trash: Trash2,
  "trending-up": TrendingUp,
  truck: Truck,
  "truck-delivery": Truck,
  upload: Upload,
  user: User,
  "user-circle": CircleUser,
  users: Users,
  "users-minus": UserMinus,
  wallet: Wallet,
  world: Globe,
  x: X,
};

const BASE_CLASS = "app-icon";

/**
 * Accepts the legacy Tabler names ("ti-home", "home", or "ti ti-home text-sm")
 * so icon names kept in config objects keep working unchanged.
 */
export default function Icon({ name, className = "", ...props }) {
  const tokens = String(name || "").trim().split(/\s+/).filter((token) => token !== "ti");
  const iconToken = tokens.find((token) => token.startsWith("ti-")) || tokens[0] || "";
  const extraClasses = tokens.filter((token) => token !== iconToken).join(" ");
  const Component = ICONS[iconToken.replace(/^ti-/, "")] || Circle;
  return (
    <Component
      aria-hidden="true"
      width="1em"
      height="1em"
      {...props}
      className={[BASE_CLASS, extraClasses, className].filter(Boolean).join(" ")}
    />
  );
}
