'use client';

import { useEffect, useState } from 'react';
import * as XLSX from 'xlsx';
import { useSearchParams } from 'next/navigation';

const price = (row, key) => Number(row[key] ?? 0);

export default function BulkBatchPricePage() {
  const searchParams = useSearchParams();
  const [stores, setStores] = useState([]); const [brands, setBrands] = useState([]);
  const [storeId, setStoreId] = useState(searchParams.get('storeId') || ''); const [brandId, setBrandId] = useState(searchParams.get('brandId') || '');
  const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  useEffect(() => { Promise.all([fetch('/api/stores').then((r) => r.json()), fetch('/api/catalog/brands?pageSize=5000').then((r) => r.json())]).then(([s, b]) => { setStores(Array.isArray(s) ? s : s.data?.records || s.records || []); setBrands(Array.isArray(b) ? b : b.data?.records || b.records || []); }).catch(() => setMessage('Could not load stores or brands.')); }, []);
  const download = async () => { if (!storeId) return setMessage('Select a store first.'); setBusy(true); try { const qs = new URLSearchParams({ storeId, ...(brandId ? { brandId } : {}) }); const res = await fetch(`/api/inventory/batches/bulk-price?${qs}`); const json = await res.json(); if (!json.success) throw new Error(json.message); const rows = (json.data?.records || []).map((r) => ({ 'Batch ID': r.batch_id, Store: r.store_name, Brand: r.brand_name, Product: r.product_name, Barcode: r.barcode, 'Batch No': r.batch_no, Expiry: r.expiry_date, 'Current CP': r.costPrice, 'Current MRP': r.mrp, 'Current SP': r.sellingPrice, 'New CP': r.costPrice, 'New MRP': r.mrp, 'New SP': r.sellingPrice })); const wb = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(rows), 'Batch Prices'); XLSX.writeFile(wb, `batch-prices-store-${storeId}.xlsx`); setMessage(`${rows.length} active batches downloaded.`); } catch (e) { setMessage(e.message || 'Download failed.'); } finally { setBusy(false); } };
  const upload = async (event) => { const file = event.target.files?.[0]; if (!file || !storeId) return setMessage('Select a store and Excel file.'); setBusy(true); try { const workbook = XLSX.read(await file.arrayBuffer(), { type: 'array' }); const sheet = XLSX.utils.sheet_to_json(workbook.Sheets[workbook.SheetNames[0]], { defval: '' }); const rows = sheet.map((r) => ({ batchId: r['Batch ID'], barcode: r.Barcode, costPrice: price(r, 'New CP'), mrp: price(r, 'New MRP'), sellingPrice: price(r, 'New SP') })); const preview = await fetch('/api/inventory/batches/bulk-price', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ storeId, rows, preview: true }) }).then((r) => r.json()); if (!preview.success) throw new Error(preview.message); const skipped = preview.data?.skipped || 0; if (skipped) throw new Error(`Preview found ${skipped} invalid row(s). No update made.`); const applied = await fetch('/api/inventory/batches/bulk-price', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ storeId, rows }) }).then((r) => r.json()); if (!applied.success) throw new Error(applied.message); setMessage(`${applied.data?.updated || 0} batch prices updated safely.`); } catch (e) { setMessage(e.message || 'Upload failed.'); } finally { setBusy(false); event.target.value = ''; } };
  return <main className="p-6 space-y-5"><div><h1 className="text-2xl font-bold">Bulk Batch Price Update</h1><p className="text-sm text-slate-500">Only active batches in the selected store are updated. Batch ID is mandatory; barcode is verified.</p></div><div className="flex flex-wrap gap-3 items-end"><label>Store<select value={storeId} onChange={(e) => setStoreId(e.target.value)} className="block border rounded p-2"><option value="">Select store</option>{stores.map((s) => <option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Brand<select value={brandId} onChange={(e) => setBrandId(e.target.value)} className="block border rounded p-2"><option value="">All brands</option>{brands.map((b) => <option key={b.id} value={b.id}>{b.name}</option>)}</select></label><button disabled={busy} onClick={download} className="border rounded px-4 py-2">Download Excel</button><label className="border rounded px-4 py-2 cursor-pointer">Upload Filled Excel<input type="file" accept=".xlsx,.xls" onChange={upload} className="hidden" /></label></div>{message && <p className="text-sm">{message}</p>}<p className="text-xs text-slate-500">Leave the New CP/MRP/SP values unchanged for batches you do not want to modify. SP and CP cannot exceed MRP.</p></main>;
}
